ABC-63: Enable release firmware image build
apollo-fire/ccs-build pull request #81
Opened 2024-01-31 15:46 UTC by thomas-burley-bluefruit

Main change here was switching from the build command:
`com.ti.ccstudio.apps.projectBuild`
to
`org.eclipse.cdt.managedbuilder.core.headlessbuild`

The new command more reliably builds the requested configuration. It also requires the project name to be specified, so an additional parameter for that has been added to the action.

2024-01-31 15:57 UTC, grahame-student commented on .github/workflows/test_local_action.yml
> +        uses: actions/upload-artifact@v4
prefer to use the full @x.y.z tag for actions as it makes workflows more deterministic

2024-01-31 15:58 UTC, grahame-student commented on .github/workflows/test_local_action.yml
> +        uses: actions/upload-artifact@v4
prefer to use the full @x.y.z tag for actions as it makes workflows more deterministic

2024-01-31 15:59 UTC, grahame-student commented on .github/workflows/test_local_action.yml
> +        with:
You can maximise the compression level for the ti-txt files
https://github.com/actions/upload-artifact?tab=readme-ov-file#altering-compressions-level-speed-v-size

2024-01-31 15:59 UTC, grahame-student commented on .github/workflows/test_local_action.yml
> +        with:
You can maximise the compression level for the ti-txt files
https://github.com/actions/upload-artifact?tab=readme-ov-file#altering-compressions-level-speed-v-size

2024-01-31 16:00 UTC, grahame-student commented on .github/workflows/test_released_action.yml
> +        uses: actions/upload-artifact@v4
prefer to use the full @x.y.z tag for actions as it makes workflows more deterministic

2024-01-31 16:00 UTC, grahame-student commented on .github/workflows/test_released_action.yml
> +        uses: actions/upload-artifact@v4
prefer to use the full @x.y.z tag for actions as it makes workflows more deterministic

2024-01-31 16:01 UTC, grahame-student commented on .github/workflows/test_released_action.yml
> +        with:
You can maximise the compression level for the ti-txt files
https://github.com/actions/upload-artifact?tab=readme-ov-file#altering-compressions-level-speed-v-size

2024-01-31 16:01 UTC, grahame-student commented on .github/workflows/test_released_action.yml
> +        with:
You can maximise the compression level for the ti-txt files
https://github.com/actions/upload-artifact?tab=readme-ov-file#altering-compressions-level-speed-v-size

2024-01-31 16:02 UTC, grahame-student commented on README.md
bump the version numbers to v0.0.6 too

2024-01-31 16:04 UTC, grahame-student commented on action.yml
the action.yml files in the following locations also need updating:
* https://github.com/apollo-fire/ccs-build/tree/abc-63-enable-release-firmware-build/compiler/18.1.3
* https://github.com/apollo-fire/ccs-build/tree/abc-63-enable-release-firmware-build/compiler/21.6.0

2024-01-31 16:06 UTC, grahame-student requested changes
Mostly there, only a couple of small tweaks required

2024-01-31 16:14 UTC, grahame-student commented on .github/workflows/test_local_action.yml
> +          compression-level: 6
max compression is 9

2024-01-31 16:18 UTC, grahame-student commented on .github/workflows/test_local_action.yml
> +      - name: CCS Build action step  - Release
```suggestion
      - name: CCS Build action step - Release
```

2024-01-31 16:20 UTC, grahame-student approved these changes
LGTM

2024-02-01 10:10 UTC, grahame-student commented
Just had a thought, will this cause workflows transitioning from the previous version to stop working?

2024-02-01 10:15 UTC, thomas-burley-bluefruit commented
> @thomas-burley-bluefruit Just had a thought, will this cause workflows transitioning from the previous version to stop working?
> 
> If so then semver (https://semver.org/) tells us we should bump the major version number.

Yes it will because there is a new mandatory input on the action. So it should be 1.0.0 now if I'm reading that page correctly?

2024-02-01 10:15 UTC, ThatTallGuy14 approved these changes
LGTM

2024-02-01 10:29 UTC, grahame-student approved these changes
LGTM

2024-02-01 12:45 UTC, merged